
#ifndef ZIPLAB_CONFIG_VERSION_H
#define ZIPLAB_CONFIG_VERSION_H

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

#include "ziplab/basic/macros.h"

// Per
#define ZIPLAB_VERSION_MAJOR      1
#define ZIPLAB_VERSION_MINOR      0
#define ZIPLAB_VERSION_PATCH      0

#define ZIPLAB_VERSION_STR        ZIPLAB_TO_DOT3(ZIPLAB_VERSION_MAJOR, ZIPLAB_VERSION_MINOR, ZIPLAB_VERSION_PATCH)
#define ZIPLAB_VERSION            ZIPLAB_TO_VER3(ZIPLAB_VERSION_MAJOR, ZIPLAB_VERSION_MINOR, ZIPLAB_VERSION_PATCH)

#define ZIPLAB_BUILD_DATE         "2025-03-10"

#endif // ZIPLAB_CONFIG_VERSION_H
