
#ifndef ZIPLAB_CONFIG_CONFIG_POST_H
#define ZIPLAB_CONFIG_CONFIG_POST_H

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

/*
    Sanitize compiler feature availability
*/
#if !defined(ZIPLAB_IS_X86)
  #undef ZIPLAB_HAVE_MMX
  #undef ZIPLAB_HAVE_SSE
  #undef ZIPLAB_HAVE_SSE2
  #undef ZIPLAB_HAVE_SSE3
  #undef ZIPLAB_HAVE_SSSE3
  #undef ZIPLAB_HAVE_SSE4_1
  #undef ZIPLAB_HAVE_SSE4_2
  #undef ZIPLAB_HAVE_AES
  #undef ZIPLAB_HAVE_AVX
  #undef ZIPLAB_HAVE_AVX2
  #undef ZIPLAB_HAVE_FMA3
  #undef ZIPLAB_HAVE_AVX512F
  #undef ZIPLAB_HAVE_AVX512VL
  #undef ZIPLAB_HAVE_AVX512CD
  #undef ZIPLAB_HAVE_AVX512ER
  #undef ZIPLAB_HAVE_AVX512PF
  #undef ZIPLAB_HAVE_AVX512BW
  #undef ZIPLAB_HAVE_AVX512DQ
  #undef ZIPLAB_HAVE_AVX512IFMA
  #undef ZIPLAB_HAVE_AVX512VBMI
  #undef ZIPLAB_HAVE_AVX512BF16
  #undef ZIPLAB_HAVE_AVX512FP16
  #undef ZIPLAB_HAVE_AVX512VNNI
  #undef ZIPLAB_HAVE_AVX512VPOPCNTDQ
  #undef ZIPLAB_HAVE_AVX512BITALG
  #undef ZIPLAB_HAVE_AVX512VP2INTERSECT
  #undef ZIPLAB_HAVE_AVX5124FMAPS
  #undef ZIPLAB_HAVE_AVX5124VNNIW
  #undef ZIPLAB_HAVE_AVX5124VBMI2
  #undef ZIPLAB_HAVE_AVX5124GFNI
  #undef ZIPLAB_HAVE_AVX5124VPCLMULQDQ
#endif

#if !defined(ZIPLAB_IS_ARM)
  #undef ZIPLAB_HAVE_NEON
#endif

#if !defined(ZIPLAB_IS_MIPS)
  #undef ZIPLAB_HAVE_MIPS_DSP
  #undef ZIPLAB_HAVE_MIPS_DSPR2
#endif

#endif // ZIPLAB_CONFIG_CONFIG_POST_H
